{"name": "test_login", "status": "broken", "statusDetails": {"message": "TypeError: 'Logger' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x7b577490b890>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"adf6713248a2ec774a5c173ccff1fcba\")>\nlogger_creation = <Logger conftest (DEBUG)>\n\n    def test_login(self, initialize_driver,logger_creation):\n      home_page = HomePage(initialize_driver)\n>     logger = logger_creation()\nE     TypeError: 'Logger' object is not callable\n\ntests/test_login.py:18: TypeError"}, "start": 1732028902530, "stop": 1732028902531, "uuid": "4c6b6917-8161-49a0-ba98-3109d86b6636", "historyId": "2116f0ad00ab1de0effc54f114dd9496", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "47488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}