{"name": "test_login_wrong_credentials", "status": "broken", "statusDetails": {"message": "TypeError: 'Logger' object is not callable", "trace": "self = <tests.test_login.TestLogin object at 0x7b577490bed0>\ninitialize_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"adf6713248a2ec774a5c173ccff1fcba\")>\nlogger_creation = <Logger conftest (DEBUG)>\n\n    def test_login_wrong_credentials(self, initialize_driver,logger_creation):\n      home_page = HomePage(initialize_driver)\n>     logger = logger_creation()\nE     TypeError: 'Logger' object is not callable\n\ntests/test_login.py:35: TypeError"}, "start": 1732028902631, "stop": 1732028902632, "uuid": "95e9ce87-06c8-40ad-b317-d6445cdc25cb", "historyId": "914ad09e2b30d6d95189061c225a031b", "testCaseId": "914ad09e2b30d6d95189061c225a031b", "fullName": "tests.test_login.TestLogin#test_login_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "aelita-hp-pavilion"}, {"name": "thread", "value": "47488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}