{"uuid": "5988d2e9-8dae-4b4c-ae37-4f18a23d8be0", "children": ["0e9cfee5-8bd1-47ff-a1e9-7f0cfd2310f6"], "befores": [{"name": "initialize_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=130.0.6723.116)\nStacktrace:\n#0 0x5982ae2a76da <unknown>\n#1 0x5982addbbf80 <unknown>\n#2 0x5982add922ef <unknown>\n#3 0x5982ade34eed <unknown>\n#4 0x5982ade4af49 <unknown>\n#5 0x5982ade2c953 <unknown>\n#6 0x5982addfb72e <unknown>\n#7 0x5982addfc79e <unknown>\n#8 0x5982ae272f1b <unknown>\n#9 0x5982ae276eb8 <unknown>\n#10 0x5982ae26042c <unknown>\n#11 0x5982ae277a37 <unknown>\n#12 0x5982ae244fef <unknown>\n#13 0x5982ae295ad8 <unknown>\n#14 0x5982ae295ca0 <unknown>\n#15 0x5982ae2a6556 <unknown>\n#16 0x7e31eb497b5a <unknown>\n\n", "trace": "  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/aelita/Projects/some/git_project/online_shop/conftest.py\", line 10, in initialize_driver\n    driver.maximize_window()\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 532, in maximize_window\n    self.execute(command, None)\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"/home/aelita/Projects/some/git_project/online_shop/my_project_venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1731596814198, "stop": 1731596819825}], "start": 1731596814198, "stop": 1731596819933}